# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       fluid

# >> macros
# << macros

Summary:    Library for fluid and dynamic applications development with QtQuick
Version:    0.2.0.20140101.e9ea587
Release:    1
Group:      System/Libraries
License:    LGPLv2.1+
URL:        https://github.com/mauios/fluid.git
Source0:    fluid-%{version}.tar.xz
Source100:  fluid.yaml
BuildRequires:  pkgconfig(liblzma)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  cmake
BuildRequires:  python
BuildRequires:  bzip2-devel

%description
Library for fluid and dynamic applications development with QtQuick.

%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .  \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_libdir}/hawaii/qml/Fluid/
# >> files
# << files
